(cl:defpackage message_typedef-msg
  (:use )
  (:export
   "<CONTROLLERDEFAULTMSG>"
   "CONTROLLERDEFAULTMSG"
   "<CUSTOMMSG>"
   "CUSTOMMSG"
   "<CUSTOMPOINT>"
   "CUSTOMPOINT"
   "<FRONTENDONEDIRTRACKRESULT>"
   "FRONTENDONEDIRTRACKRESULT"
   "<FRONTENDTRACKRESULT>"
   "FRONTENDTRACKRESULT"
   "<LOCATORFDIMSG>"
   "LOCATORFDIMSG"
   "<PERCEPTRONDEFAULTMSG>"
   "PERCEPTRONDEFAULTMSG"
   "<PLANNERDEFAULTMSG>"
   "PLANNERDEFAULTMSG"
  ))

