(cl:in-package message_typedef-msg)
(cl:export '(HEADER-VAL
          HEADER
          IS_LOCATOR_ODOM_ERROR-VAL
          IS_LOCATOR_ODOM_ERROR
          IS_IMU_OVER_RANGE-VAL
          IS_IMU_OVER_RANGE
          IS_VISUAL_TRACK_RESULT_ERROR-VAL
          IS_VISUAL_TRACK_RESULT_ERROR
          IS_LIDAR_SCAN_ERROR-VAL
          IS_LIDAR_SCAN_ERROR
          IS_CPU_USAGE_OVER_RANGE-VAL
          IS_CPU_USAGE_OVER_RANGE
          ODOM_HORIZONTAL_VELOCITY_M_S-VAL
          ODOM_HORIZONTAL_VELOCITY_M_S
          ODOM_VERTICAL_VELOCITY_M_S-VAL
          ODOM_VERTICAL_VELOCITY_M_S
          ODOM_ROLL_DEG-VAL
          ODOM_ROLL_DEG
          ODOM_PITCH_DEG-VAL
          ODOM_PITCH_DEG
          IMU_NORM_ACCEL_M_S2-VAL
          IMU_NORM_ACCEL_M_S2
          LIDAR_RATIO_OF_INVALID_POINTS-VAL
          LIDAR_RATIO_OF_INVALID_POINTS
          CPU_USAGE_PERCENTAGE-VAL
          CPU_USAGE_PERCENTAGE
))