Header header             # ROS standard message header
bool is_locator_odom_error
bool is_imu_over_range
bool is_visual_track_result_error
bool is_lidar_scan_error
bool is_cpu_usage_over_range
float32 odom_horizontal_velocity_m_s
float32 odom_vertical_velocity_m_s
float32 odom_roll_deg
float32 odom_pitch_deg
float32 imu_norm_accel_m_s2
float32 lidar_ratio_of_invalid_points
float32[] cpu_usage_percentage
